services:
  web:
    image: nekocho/guestbook
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db 
  db:
    image: postgres
    environment:
      POSTGRES_DB: Database
      POSTGRES_USER: ebroot
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"